import 'dart:ui';

/// Global constants used throughout the app.
/// ⚠️ WARNING: Expect breaking changes
class Constants {

  /// The length of the verification code.
  static const int bankingVerificationCodeLength = 8;

  /// The allowed bank transfer methods supported by the app.
  static const List<String> bankingMethods = ["Bank Transfer", "Cashapp", "PayPal", "Skrill", "Payoneer", "Bitcoin", "Ethereum", "Litecoin", "Ripple"];

  /// The currencies supported by the app.
  static const List<String> bankingCurrency = ["GBP", "USD", "EUR"];

  /// Symbols: are you a sex symbol?
  static const List<String> bankingCurrencySymbol = ["£", "\$", "€"];

  /// Error messages
  static const Map<String, String> errorMessages = {
    //
  };

  /// Info text
  static const Map<String, String> infoText = {
    //
  };

  /// Ad Statuses
  static const List<String> adStatuses = [
    "Not Verified",
    "Pending",
    "Ready",
    "Active",
    "Disabled",
  ];

  static const int adStatusNotVerified = 0;
  static const int adStatusPending = 1;
  static const int adStatusReady = 2;
  static const int adStatusActive = 3;
  static const int adStatusDisabled = 4;

  /// Ad space sizes
  static const List<String> adSpaceSizes = [
    "Small",
    "Small",
    "Medium",
    "Large"
  ];

  /// Car makes list
  static const List<String> carMakes = [
    "Abarth",
    "AC",
    "Acura",
    "Aixam",
    "Alfa Romeo",
    "Ariel",
    "Arrinera",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Bugatti",
    "Buick",
    "Cadillac",
    "Caterham",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Corvette",
    "Dacia",
    "Daf",
    "Daihatsu",
    "Dodge",
    "DR Motor",
    "Elfin",
    "Ferrari",
    "Fiat",
    "Ford",
    "Gaz",
    "Geely",
    "Gillet",
    "Ginetta",
    "General Motors",
    "GMC",
    "Great Wall",
    "Gumpert",
    "Hennessey logo",
    "Holden",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Joss",
    "Kia",
    "Koenigsegg",
    "Lada",
    "Lamborghini",
    "Lancia",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Luxgen",
    "Mahindra",
    "Maruti Suzuki",
    "Maserati",
    "Maybach",
    "Mazda",
    "Mclaren",
    "Mercedes",
    "MG",
    "Mini",
    "Mitsubishi",
    "Morgan Motor",
    "Mustang logo",
    "Nissan",
    "Noble",
    "Opel",
    "Pagani",
    "Panoz",
    "Perodua",
    "Peugeot",
    "Piaggio",
    "Pininfarina",
    "Porsche",
    "Proton",
    "Renault",
    "Reva",
    "Rimac",
    "Rolls Royce",
    "Ruf logo",
    "Saab",
    "Scania",
    "Scion",
    "Seat",
    "Shelby",
    "Skoda",
    "Smart",
    "Spyker",
    "Ssangyong",
    "SSC",
    "Subaru",
    "Suzuki",
    "Tata",
    "Tatra",
    "Tesla",
    "Toyota",
    "Tramontana",
    "Troller",
    "TVR",
    "UAZ",
    "Vandenbrink",
    "Vauxhall",
    "Vector Motors",
    "Venturi",
    "Volkswagen",
    "Volvo",
    "Wiesmann",
    "Zagato",
    "Zaz",
    "Zil",
    "Other"
  ];

  /// Car body year list
  static const List<int> carYearsChart = [
    2024,
    2023,
    2022,
    2021,
    2020,
    2019,
    2018,
    2017,
    2016,
    2015,
    2014,
    2013,
    2012,
    2011,
    2010,
    2009,
    2008,
    2007,
    2006,
    2005,
    2004,
    2003,
    2002,
    2001,
    2000,
    1999,
    1998,
    1997,
    1996,
    1995,
    1994,
    1993,
    1992,
    1991,
    1990,
    1989,
    1988,
    1987,
    1986,
    1985,
    1984,
    1983,
    1982,
    1981,
    1980,
    1979,
    1978,
    1977,
    1976,
    1975,
    1974,
    1973,
    1972,
    1971,
    1970,
    1969,
    1968,
    1967,
    1966,
    1965,
    1964,
    1963,
    1962,
    1961,
    1960,
    1959,
    1958,
    1957,
    1956,
    1955,
    1954,
    1953,
    1952,
    1951,
    1950,
    1949,
    1948,
    1947,
    1946,
    1945,
    1944,
    1943,
    1942,
    1941,
    1940,
    1939,
    1938,
    1937,
    1936,
    1935,
    1934,
    1933,
    1932,
    1931,
    1930,
    1929,
    1928,
    1927,
    1926,
    1925,
    1924,
    1923,
    1922,
    1921,
    1920,
    1919,
    1918,
    1917,
    1916,
    1915,
    1914,
    1913,
    1912,
    1911,
    1910,
    1909,
    1908,
    1907,
    1906,
    1905,
    1904,
    1903,
    1902,
    1901,
    1900
  ];

  /// Car parking types
  /// @todo will need translation
  static const List<String> carParkingTypes = ["Private Parking", "Driveway", "On Street", "Garage"];

  /// Car body colour list
  /// @todo will need translation
  static const List<String> carColours = [
    "Black",
    "Blue",
    "Brown",
    "Beige",
    "Copper",
    "Cream",
    "Gold",
    "Green",
    "Grey",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "Silver",
    "White",
    "Yellow",
    "Other"
  ];

  /// Car colours map
  /// @todo will need translation
  static const Map<String, Color> carColoursMap = {
    "Black": Color(0xFF000000),
    "Blue": Color(0xFF0000FF),
    "Brown": Color(0xFFA52A2A),
    "Beige": Color(0xFFD2B48C),
    "Copper": Color(0xFFB87333),
    "Cream": Color(0xFFFFFDD0),
    "Gold": Color(0xFFD4AF37),
    "Green": Color(0xFF008000),
    "Grey": Color(0xFF808080),
    "Orange": Color(0xFFFFA500),
    "Pink": Color(0xFFFFC0CB),
    "Purple": Color(0xFF800080),
    "Red": Color(0xFFFF0000),
    "Silver": Color(0xFFC0C0C0),
    "White": Color(0xFFFFFFFF),
    "Yellow": Color(0xFFFFFF00),
    "Other": Color(0xFF000000)
  };

  /// Fuel types
  /// @todo will need translation
  static const List<String> carFuelTypes = [
    "Petrol",
    "Diesel",
    "Electric",
    "Hybrid",
    "Bio-Diesel",
    "Natural Gas",
    "Hydrogen",
    "Other"
  ];

  /// House visibilities
  /// @todo will need translation
  static const List<String> houseVisibilities = [
    "Visible from street",
    "Partially visible from street",
    "Not visible from street"
  ];

  /// House residency type
  /// @todo will need translation
  static const List<String> houseResidents = [
    "Owner",
    "Tenant",
    "Business Owner",
    "Business Tenant",
    "Property Manager",
    "Real Estate Agent",
    "Other",
  ];

  /// House types
  /// @todo will need translation
  static const List<String> houseTypes = [
    "Flat",
    "Detached",
    "Semi-Detached",
    "Terraced",
    "Bungalow",
    "Modular",
    "Other"
  ];

  /// List of mobile prefixes
  static const List<Map<String, String>> mobilePrefixes = [{
    "UK": "+44",
    "US": "+1",
    // Europeans
    "Austria": "+43",
    "Belgium": "+32",
    "Bulgaria": "+359",
    "Croatia": "+385",
    "Cyprus": "+357",
    "Czech Republic": "+420",
    "Denmark": "+45",
    "Estonia": "+372",
    "Finland": "+358",
    "France": "+33",
    "Germany": "+49",
    "Greece": "+30",
    "Hungary": "+36",
    "Ireland": "+353",
    "Italy": "+39",
    "Latvia": "+371",
    "Lithuania": "+370",
    "Luxembourg": "+352",
    "Malta": "+356",
    "Netherlands": "+31",
    "Poland": "+48",
    "Portugal": "+351",
    "Romania": "+40",
    "Slovakia": "+421",
    "Slovenia": "+386",
    "Spain": "+34",
    "Sweden": "+46",
    "Australia": "+61",
    "New Zealand": "+64",
    "Canada": "+1",
    "China": "+86",
    "India": "+91",
    "Japan": "+81",
    "Pakistan": "+92",
    "Russia": "+7",
    "South Africa": "+27",
    "South Korea": "+82",
    "Turkey": "+90",
    "United Arab Emirates": "+971",
    "Afghanistan": "+93",
    "Albania": "+355",
    "Algeria": "+213",
    "American Samoa": "+1",
    "Andorra": "+376",
    "Angola": "+244",
    "Anguilla": "+1",
    "Antigua and Barbuda": "+1",
    "Argentina": "+54",
    "Armenia": "+374",
    "Aruba": "+297",
    "Azerbaijan": "+994",
    "Bahamas": "+1",
    "Bahrain": "+973",
    "Bangladesh": "+880",
    "Barbados": "+1",
    "Belarus": "+375",
    "Belize": "+501",
    "Benin": "+229",
    "Bermuda": "+1",
    "Bhutan": "+975",
    "Bolivia": "+591",
    "Bosnia and Herzegovina": "+387",
    "Botswana": "+267",
    "Brazil": "+55",
    "British Indian Ocean Territory": "+246",
    "British Virgin Islands": "+1",
    "Brunei": "+673",
    "Burkina Faso": "+226",
    "Burundi": "+257",
    "Cambodia": "+855",
    "Cameroon": "+237",
    "Cape Verde": "+238",
    "Cayman Islands": "+1",
    "Central African Republic": "+236",
    "Chad": "+235",
    "Chile": "+56",
    "Christmas Island": "+61",
    "Cocos Islands": "+61",
    "Colombia": "+57",
    "Comoros": "+269",
    "Cook Islands": "+682",
    "Costa Rica": "+506",
    "Cuba": "+53",
    "Curacao": "+599",
    "Djibouti": "+253",
    "Dominica": "+1",
    "Dominican Republic": "+1",
    "Ecuador": "+593",
    "Egypt": "+20",
    "El Salvador": "+503"
  }];

  /// List of cities, by county
  /// @todo may need translation (?)
  static const Map<String, Map<String, String>> cities = {
    "UK": {
      "Aberdare": "Mid Glamorgan",
      "Aberdeen": "Aberdeenshire",
      "Aberdovey": "Gwynedd",
      "Abergavenny": "Gwent",
      "Abergele": "Clwyd",
      "Abertillery": "Gwent",
      "Aberystwyth": "Dyfed",
      "Abingdon": "Oxfordshire",
      "Accrington": "Lancashire",
      "Airdrie": "Lanarkshire",
      "Alcester": "Warwickshire",
      "Aldeburgh": "Suffolk",
      "Alderley Edge": "Cheshire",
      "Aldershot": "Hampshire",
      "Alfreton": "Derbyshire",
      "Alness": "Ross-shire",
      "Alnwick": "Northumberland",
      "Alresford": "Hampshire",
      "Alston": "Cumbria",
      "Alton": "Hampshire",
      "Altrincham": "Cheshire",
      "Ambleside": "Cumbria",
      "Amersham": "Buckinghamshire",
      "Amesbury": "Wiltshire",
      "Ammanford": "Carmarthenshire",
      "Andover": "Hampshire",
      "Anstruther": "Fife",
      "Antrim": "Co Antrim",
      "Appleby-in-Westmorland": "Cumbria",
      "Arbroath": "Angus",
      "Ardrossan": "Ayrshire",
      "Armagh": "Co Armagh",
      "Arthog": "Gwynedd",
      "Arundel": "West Sussex",
      "Ascot": "Berkshire",
      "Ashbourne": "Derbyshire",
      "Ashburton": "Devon",
      "Ashford": "Middlesex",
      "Ashington": "Northumberland",
      "Ashtead": "Surrey",
      "Ashton-under-Lyne": "Greater Manchester",
      "Attleborough": "Norfolk",
      "Aviemore": "Inverness-shire",
      "Axminster": "Devon",
      "Aylesbury": "Buckinghamshire",
      "Ayr": "Ayrshire",
      "Bala": "Gwynedd",
      "Baldock": "Hertfordshire",
      "Ballachulish": "Argyll",
      "Ballycastle": "Co Antrim",
      "Ballyclare": "Co Antrim",
      "Ballymena": "Co Antrim",
      "Ballymoney": "Co Antrim",
      "Bamburgh": "Northumberland",
      "Bamstaple": "Devon",
      "Banbridge": "Co Down",
      "Banbury": "Oxfordshire",
      "Banchory": "Kincardineshire",
      "Banff": "Aberdeenshire",
      "Bangor": "Gwynedd",
      "Banstead": "Surrey",
      "Barking": "Essex",
      "Barmouth": "Gwynedd",
      "Barnard Castle": "Co Durham",
      "Barnet": "Hertfordshire",
      "Barnsley": "South Yorkshire",
      "Barnstaple": "Devon",
      "Barry": "South Glamorgan",
      "Barrow-in Furness": "Cumbria",
      "Barton-upon-Humber": "South Humberside",
      "Basildon": "Essex",
      "Basingstoke": "Hampshire",
      "Bath": "Avon",
      "Bathgate": "West Lothian",
      "Battle": "East Sussex",
      "Beaumaris": "Gwynedd",
      "Beccles": "Suffolk",
      "Beckenham": "Kent",
      "Bedale": "North Yorkshire",
      "Bedford": "Bedfordshire",
      "Belfast": "Belfast",
      "Belvedere": "Kent",
      "Benneet": "Essex",
      "Berkhamsted": "Hertfordshire",
      "Berwick-on-Tweed": "Northumberland",
      "Betws-y-Coed": "Conwy",
      "Beverley": "North Humberside",
      "Bewdley": "Worcestershire",
      "Bexhill-on-Sea": "East Sussex",
      "Bicester": "Oxfordshire",
      "Bideford": "Devon",
      "Biggar": "Lanarkshire",
      "Biggleswade": "Bedfordshire",
      "Billericay": "Essex",
      "Billingshurst": "West Sussex",
      "Bingley": "West Yorkshire",
      "Birkenhead": "Merseyside",
      "Birmingham": "West Midlands",
      "Bishop Auckland": "Co Durham",
      "Bishops Castle": "Shropshire",
      "Bishop's Stortford": "Hertfordshire",
      "Bishops Waltham": "Hampshire",
      "Blackburn": "Lancashire",
      "Blackpool": "Lancashire",
      "Blaenau Ffestiniog": "Gwynedd",
      "Blairgowrie": "Perthshire",
      "Blandford Forum": "Dorset",
      "Blaydon-on-Tyne": "Tyne and Wear",
      "Bodmin": "Cornwall",
      "Bognor Regis": "West Sussex",
      "Boldon Colliery": "Tyne and Wear",
      "Bolton": "Lancashire",
      "Bonnyrigg": "Midlothian",
      "Bootle": "Merseyside",
      "Bordon": "Hampshire",
      "Borehamwood": "Hertfordshire",
      "Boston": "Lincolnshire",
      "Botness": "West Lothian",
      "Bourne": "Lincolnshire",
      "Bournemouth": "Dorset",
      "Brackley": "Northamptonshire",
      "Bracknell": "Berkshire",
      "Bradford": "West Yorkshire",
      "Braintree": "Essex",
      "Brampton": "Cumbria",
      "Braunton": "Devon",
      "Brecon": "Powys",
      "Brentford": "Middlesex",
      "Brentwood": "Essex",
      "Bridgend": "Mid Glamorgan",
      "Bridgnorth": "Shropshire",
      "Bridgwater": "Somerset",
      "Bridlington": "North Humberside",
      "Bridport": "Dorset",
      "Brigg": "Lincolnshire",
      "Brighouse": "West Yorkshire",
      "Brighton": "East Sussex",
      "Bristol": "Avon",
      "Brixham": "Devon",
      "Broadford": "Isle of Skye",
      "Broadstairs": "Kent",
      "Broadway": "Hereford and Worcester",
      "Brockenhurst": "Hampshire",
      "Brodick": "Isle of Arran",
      "Bromley": "Kent",
      "Bromsgrove": "Hereford and Worcester",
      "Brooke": "Norfolk",
      "Broxburn": "West Lothian",
      "Buckfastleigh": "Devon",
      "Buckhurst Hill": "Essex",
      "Buckie": "Banffshire",
      "Buckingham": "Buckinghamshire",
      "Bude": "Cornwall",
      "Budleigh Salterton": "Devon",
      "Builth Wells": "Powys",
      "Bunessan": "Isle of Mull",
      "Bungay": "Suffolk",
      "Burgess Hill": "West Sussex",
      "Burnham-on-Sea": "Somerset",
      "Burnley": "Lancashire",
      "Burton-on-Trent": "Staffordshire",
      "Bury": "Lancashire",
      "Bury St Edmunds": "Suffolk",
      "Bushmills": "Co Antrim",
      "Buxton": "Derbyshire",
      "Caernarvon": "Gwynedd",
      "Caerphilly": "Mid Glamorgan",
      "Calne": "Wiltshire",
      "Camberley": "Surrey",
      "Cambridge": "Cambridgeshire",
      "Camelford": "Cornwall",
      "Campbeltown": "Argyll",
      "Cannock": "Staffordshire",
      "Canterbury": "Kent",
      "Cardiff": "South Glamorgan",
      "Cardigan": "Dyfed",
      "Carlisle": "Cumbria",
      "Carloway": "Isle of Lewis",
      "Carluke": "Lanarkshire",
      "Carmarthen": "Dyfed",
      "Carnforth": "Lancashire",
      "Carrickfergus": "Co Antrim",
      "Carshalton": "Surrey",
      "Castle Douglas": "Kirkcudbrightshire",
      "Castlederg": "Co Tyrone",
      "Castletown": "Isle of Man",
      "Castlewellan": "Co Down",
      "Caterham": "Surrey",
      "Cemmaes Bay": "Gwynedd",
      "Cemmaes Road": "Gwynedd",
      "Cerne Abbas": "Dorset",
      "Chard": "Somerset",
      "Chatham": "Kent",
      "Chatteris": "Cambridgeshire",
      "Cheadle": "Cheshire",
      "Cheam": "Surrey",
      "Cheddar": "Somerset",
      "Chelmsford": "Essex",
      "Cheltenham": "Gloucestershire",
      "Chepstow": "Gwent",
      "Chertsey": "Surrey",
      "Chesham": "Buckinghamshire",
      "Chester": "Cheshire",
      "Chester-le-Street": "Co Durham",
      "Chesterfield": "Derbyshire",
      "Chichester": "West Sussex",
      "Chippenham": "Wiltshire",
      "Chipping Norton": "Oxfordshire",
      "Chipping Sodbury": "Gloucestershire",
      "Chorley": "Lancashire",
      "Christchurch": "Dorset",
      "Church Stretton": "Shropshire",
      "Cinderford": "Gloucestershne",
      "Cirencester": "Gloucestershire",
      "Clacton-on-Sea": "Essex",
      "Cleethorpes": "South Humberside",
      "Clevedon": "Avon",
      "Clitheroe": "Lancashire",
      "Clogher": "Co Tyrone",
      "Clopton": "Northamptonshire",
      "Coalville": "Leicestershire",
      "Coatbridge": "Lanarkshire",
      "Cobham": "Surrey",
      "Cockermouth": "Cumbria",
      "Colchester": "Essex",
      "Coleshill": "Warwickshire",
      "Coleraine": "Co Londonderry",
      "Colwyn Bay": "Clwyd",
      "Congleton": "Cheshire",
      "Coniston": "Cumbria",
      "Consett": "Co Durham",
      "Conwy": "Gwynedd",
      "Cookstown": "Co Tyrone",
      "Coppull": "Lancashire",
      "Corbridge": "Northumberland",
      "Corby": "Northamptonshire",
      "Corwen": "Clwyd",
      "Coulsdon": "Surrey",
      "Coventry": "West Midlands",
      "Craigavon": "Co Armagh",
      "Cramlington": "Northumberland",
      "Cranbrook": "Kent",
      "Cranleigh": "Surrey",
      "Craven Arms": "Shropshire",
      "Crawley": "West Sussex",
      "Crediton": "Devon",
      "Crewe": "Cheshire",
      "Crieff": "Perthshire",
      "Cromer": "Norfolk",
      "Crowborough": "East Sussex",
      "Croy": "Inverness-shire",
      "Croydon": "Surrey",
      "Crumlin": "Co Antrim",
      "Cullompton": "Devon",
      "Cumnock": "East Ayrshire",
      "Cupar": "Fife",
      "Cwmbran": "Gwent",
      "Dagenham": "Essex",
      "Dalbeattie": "Kirkcudbrightshire",
      "Dalmally": "Argyll",
      "Dalry": "Ayrshire",
      "Darlington": "Co Durham",
      "Dartford": "Kent",
      "Darvel": "Ayrshire",
      "Daventry": "Northamptonshire",
      "Deal": "Kent",
      "Deeside": "Clwyd",
      "Derby": "Derbyshire",
      "Dereham": "Norfolk",
      "Devizes": "Wiltshire",
      "Dewsbury": "West Yorkshire",
      "Didcot": "Oxfordshire",
      "Dinas Powis": "South Glamorgan",
      "Dingwall": "Ross-shire",
      "Diss": "Norfolk",
      "Dolgellau": "Gwynedd",
      "Doncaster": "South Yorkshire",
      "Dorchester": "Dorset",
      "Dorking": "Surrey",
      "Dornoch": "Sutherland",
      "Douglas": "Isle of Man",
      "Dover": "Kent",
      "Downham Market": "Norfolk",
      "Downpatrick": "Co Down",
      "Driffield": "North Humberside",
      "Droitwich": "Hereford and Worcester",
      "Dromore": "Co Down",
      "Dudley": "West Midlands",
      "Dulverton": "Somerset",
      "Dumbarton": "Dunbartonshire",
      "Dumfries": "Dumfriesshire",
      "Dunbar": "East Lothian",
      "Dunblane": "Perthshire",
      "Dundee": "Angus",
      "Dunfermline": "Fife",
      "Dungannon": "Co Tyrone",
      "Dunkeld": "Perthshire",
      "Dunmow": "Essex",
      "Dunmurry": "Belfast",
      "Dunoon": "Argyll",
      "Duns": "Berwickshire",
      "Dunstable": "Bedfordshire",
      "Durham": "Co Durham",
      "Dursley": "Gloucestershire",
      "Easingwold": "North Yorkshire",
      "East Grinstead": "West Sussex",
      "East Kilbride": "South Lanarkshire",
      "East Molesey": "Surrey",
      "Eastbourne": "East Sussex",
      "Eastleigh": "Hampshire",
      "Ebbsfleet": "Kent",
      "Ebbw Vale": "Gwent",
      "Edenbridge": "Kent",
      "Edgware": "Middlesex",
      "Edinburgh": "Edinburgh",
      "Egham": "Surrey",
      "Elgin": "Morayshire",
      "Ellesmere Port": "Cheshire",
      "Ellon": "Aberdeenshire",
      "Ely": "Cambridgeshire",
      "Emsworth": "Hampshire",
      "Enfeld": "Middlesex",
      "Enniskillen": "Co Fermanagh",
      "Epping": "Essex",
      "Epsom": "Surrey",
      "Erith": "Kent",
      "Esher": "Surrey",
      "Evesham": "Worcestershire",
      "Exeter": "Devon",
      "Exmouth": "Devon",
      "Fakenham": "Norfolk",
      "Falkirk": "Stirlingshire",
      "Falmouth": "Cornwall",
      "Fareham": "Hampshire",
      "Faringdon": "Oxfordshire",
      "Farnborough": "Hampshire",
      "Farnham": "Surrey",
      "Felixstowe": "Suffolk",
      "Fishguard": "Dyfed",
      "Fivemiletown": "Co Tyrone",
      "Fleet": "Hampshire",
      "Fleetwood": "Lancashire",
      "Flint": "Clwyd",
      "Folkestone": "Kent",
      "Forfar": "Angus",
      "Fort William": "Inverness-shire",
      "Fortrose": "Ross-shire",
      "Fowey": "Cornwall",
      "Fraserburgh": "Aberdeenshire",
      "Freshwater": "Isle of Wight",
      "Frinton-on-Sea": "Essex",
      "Frome": "Somerset",
      "Gainsborough": "Lincolnshire",
      "Gairloch": "Ross-shire",
      "Galasheils": "Selkirkshire",
      "Garstang": "Lancashire",
      "Gateshead": "Tyne and Wear",
      "Gerrards Cross": "Buckinghamshire",
      "Gillingham": "Kent",
      "Girvan": "South Ayrshire",
      "Glamorgan": "Rotherham",
      "Glasgow": "Glasgow",
      "Glastonbury": "Somerset",
      "Glenrothes": "Fife",
      "Glossop": "Derbyshire",
      "Gloucester": "Gloucestershire",
      "Godalming": "Surrey",
      "Godstone": "Surrey",
      "Goole": "East Riding of Yorkshire",
      "Gosforth": "Cumbria",
      "Gosport": "Hampshire",
      "Grange-over-Sands": "Cumbria",
      "Grangemouth": "Midlothian",
      "Grantham": "Lincolnshire",
      "Gravesend": "Kent",
      "Grays Thurrock": "Essex",
      "Great Dunmow": "Essex",
      "Great Missenden": "Buckinghamshire",
      "Great Yarmouth": "Norfolk",
      "Greenford": "Middlesex",
      "Greenock": "Renfrewshire",
      "Gretna": "Dumfriesshire",
      "Grimsby": "South Humberside",
      "Guernsey": "Channel Islands",
      "Guildford": "Surrey",
      "Guisborough": "North Yorkshire",
      "Guiseley": "West Yorkshire",
      "Gullane": "East Lothian",
      "Hamilton": "Lanark shire",
      "Haddington": "East Lothian",
      "Hailsham": "East Sussex",
      "Halesowen": "West Midlands",
      "Halifax": "West Yorkshire",
      "Halstead": "Essex",
      "Haltwhistle": "Northumberland",
      "Hampton": "Middlesex",
      "Harlow": "Essex",
      "Harpenden": "Hertfordshire",
      "Harrogate": "North Yorkshire",
      "Harrow": "Middlesex",
      "Hartlepool": "Cleveland",
      "Harwich": "Essex",
      "Haslemere": "Surrey",
      "Hassocks": "West Sussex",
      "Hastings": "East Sussex",
      "Hatfield": "Hertfordshire",
      "Hathersage": "Derbyshire",
      "Havant": "Hampshire",
      "Haverfordwest": "Pembrokeshire",
      "Haverhill": "Suffolk",
      "Hawick": "Roxburghshire",
      "Hawkshead": "Cumbria",
      "Hay-on-Wye": "Powys",
      "Hayes": "Middlesex",
      "Hayling Island": "Hampshire",
      "Haywards Heath": "West Sussex",
      "Heanor": "Derbyshire",
      "Heathfield": "East Sussex",
      "Helensburgh": "Dunbartonshire",
      "Helmsley": "North Yorkshire",
      "Helston": "Cornwall",
      "Hemel Hempstead": "Hertfordshire",
      "Henfield": "West Sussex",
      "Henley-on-Thames": "Oxfordshire",
      "Hereford": "Hereford and Worcester",
      "Herne Bay": "Kent",
      "Hertford": "Hertfordshire",
      "Hessle": "North Humberside",
      "Hexham": "Northumberland",
      "Heywood": "Lancashire",
      "High Wycombe": "Buckinghamshire",
      "Highbridge": "Somerset",
      "Hillsborough": "Co Down",
      "Hinckley": "Leicestershire",
      "Hindhead": "Surrey",
      "Hitchin": "Hertfordshire",
      "Hockley": "Essex",
      "Hoddesdon": "Hertfordshire",
      "Holbeach": "Lincolnshire",
      "Holmes Chapel": "Cheshire",
      "Holsworthy": "Devon",
      "Holt": "Norfolk",
      "Holyhead": "Gwynedd",
      "Holywood": "Co Down",
      "Honington": "Lincolnshire",
      "Honiton": "Devon",
      "Hook": "Hampshire",
      "Horley": "Surrey",
      "Hornby": "Lancashire",
      "Hornchurch": "Essex",
      "Hornsea": "East Riding of Yorkshire",
      "Horsham": "West Sussex",
      "Houghton le Spring": "Tyne and Wear",
      "Hounslow": "Middlesex",
      "Hove": "East Sussex",
      "Huddersfield": "West Yorkshire",
      "Hull": "North Humberside",
      "Hungerford": "Berkshire",
      "Hunstanton": "Norfolk",
      "Huntingdon": "Cambridgeshire",
      "Huntly": "Aberdeenshire",
      "Hyde": "Cheshire",
      "Hythe": "Kent",
      "Ilford": "Essex",
      "Ilfracombe": "Devon",
      "Ilkeston": "Derbyshire",
      "Ilkley": "West Yorkshire",
      "Immingham": "South Humberside",
      "Ingatestone": "Essex",
      "Insch": "Aberdeenshire",
      "Inveraray": "Argyll",
      "Inverness": "Inverness-shire",
      "Inverurie": "Aberdeenshire",
      "Iona": "Isle of Iona",
      "Ipstones": "Staffordshire",
      "Ipswich": "Suffolk",
      "Ironbridge": "Shropshire",
      "Isle of Wight": "Isle of Wight",
      "Isleworth": "Middlesex",
      "Jersey": "Channel Islands",
      "Johnstone": "Renfrewshire",
      "Keighley": "West Yorkshire",
      "Kelso": "Roxburghshire",
      "Kendal": "Cumbria",
      "Kenilworth": "Warwickshire",
      "Keswick": "Cumbria",
      "Kettering": "Northamptonshire",
      "Kidderminster": "Hereford and Worcester",
      "Kilbirnie": "Ayrshire",
      "Killin": "Perthshire",
      "Killingholme": "Lincolnshire",
      "Kilmacolm": "Renfrewshire",
      "Kilmarnock": "Ayrshire",
      "King's Lynn": "Norfolk",
      "Kings Langley": "Hertfordshire",
      "Kingsbridge": "Devon",
      "Kingston upon Thames": "Surrey",
      "Kingswinford": "West Midlands",
      "Kington": "Herefordshire",
      "Kingussie": "Inverness-shire",
      "Kirkby Stephen": "Cumbria",
      "Kirkcaldy": "Fife",
      "Kirkwhelpington": "Northumberland",
      "Kirriemuir": "Angus",
      "Knighton": "Powys",
      "Knutsford": "Cheshire",
      "Kyle": "Ross-shire",
      "Kyleakin": "Isle of Skye",
      "Laindon": "Essex",
      "Lairg": "Sutherland",
      "Lampeter": "Ceredigion",
      "Lanark": "Lanarkshire",
      "Lancaster": "Lancashire",
      "Lancing": "West Sussex",
      "Lapworth": "Warwickshire",
      "Larbert": "Stirlingshire",
      "Latheron": "Caithness",
      "Launceston": "Cornwall",
      "Leamington Spa": "Warwickshire",
      "Leatherhead": "Surrey",
      "Ledbury": "Hereford and Worcester",
      "Leeds": "West Yorkshire",
      "Leicester": "Leicestershire",
      "Leigh": "Lancashire",
      "Leigh-on-Sea": "Essex",
      "Leighton Buzzard": "Bedfordshire",
      "Leiston": "Suffolk",
      "Leominster": "Hereford and Worcester",
      "Lerwick": "Isle of Shetland",
      "Letchworth": "Hertfordshire",
      "Lewes": "East Sussex",
      "Leyburn": "North Yorkshire",
      "Leyland": "Lancashire",
      "Lichfield": "Staffordshire",
      "Lightwater": "Surrey",
      "Limavady": "Co Londonderry",
      "Lincoln": "Lincolnshire",
      "Lingfield": "Surrey",
      "Liphook": "Hampshire",
      "Lisburn": "Co Antrim",
      "Liskeard": "Cornwall",
      "Liss": "Hampshire",
      "Littleborough": "Lancashire",
      "Littlehampton": "West Sussex",
      "Liverpool": "Merseyside",
      "Livingston": "West Lothian",
      "Llanarth": "Ceredigion",
      "Llanbedr": "Gwynedd",
      "Llandeilo": "Carmarthenshire",
      "Llandovery": "Carmarthenshire",
      "Llandrindod Wells": "Powys",
      "Llandudno": "Gwynedd",
      "Llandysul": "Dyfed",
      "Llanelli": "Dyfed",
      "Llangollen": "Clwyd",
      "Llanidloes": "Powys",
      "Llanon": "Ceredigion",
      "Llanrwst": "Gwynedd",
      "Llantwit": "South Glamorgan",
      "Llanwrda": "Dyfed",
      "Llanwrtyd Wells": "Powys",
      "Loanhead": "Midlothian",
      "Lochboisdale": "Isle of Uist",
      "Lochcarron": "Ross-shire",
      "Lochgilphead": "Argyll",
      "Lochwinnoch": "Renfrewshire",
      "Lockerbie": "Dumfriesshire",
      "London": "London",
      "Londonderry": "Co Londonderry",
      "Loughborough": "Leicestershire",
      "Loughton": "Essex",
      "Louth": "Lincolnshire",
      "Lowestoft": "Suffolk",
      "Ludlow": "Shropshire",
      "Lurgan": "Co Antrim",
      "Luton": "Bedfordshire",
      "Lutterworth": "Leicestershire",
      "Lydney": "Gloucestershire",
      "Lymington": "Hampshire",
      "Lyndhurst": "Hampshire",
      "Lynton": "Devon",
      "Lytham StAnnes": "Lancashire",
      "Macclesfield": "Cheshire",
      "Machynlleth": "Powys",
      "Madingley": "Cambridgeshire",
      "Maesteg": "Mid Glamorgan",
      "Magharafelt": "Co Londonderry",
      "Maidenhead": "Berkshire",
      "Maidstone": "Kent",
      "Maldon": "Essex",
      "Malmesbury": "Wiltshire",
      "Malpas": "Cheshire",
      "Malton": "North Yorkshire",
      "Malvern": "Hereford and Worcester",
      "Manchester": "Greater Manchester",
      "Mansfield": "Nottinghamshire",
      "March": "Cambridgeshire",
      "Margate": "Kent",
      "Market Drayton": "Shropshire",
      "Market Harborough": "Leicestershire",
      "Market Rasen": "Lincolnshire",
      "Market Weighton": "East Riding of Yorkshire",
      "Marlborough": "Wiltshire",
      "Marlow": "Buckinghamshire",
      "Martin": "Lincolnshire",
      "Maryport": "Cumbria",
      "Matlock": "Derbyshire",
      "Maud": "Aberdeenshire",
      "Medway": "Kent",
      "Meifod": "Powys",
      "Melksham": "Wiltshire",
      "Melton Mowbray": "Leicestershire",
      "Mere": "Wiltshire",
      "Meriden": "West Midlands",
      "Merthyr Tydfil": "Mid Glamorgan",
      "Mexborough": "South Yorkshire",
      "Middlesbrough": "Cleveland",
      "Middlewich": "Cheshire",
      "Midhurst": "West Sussex",
      "Mildenhall": "Suffolk",
      "Milford Haven": "Pembrokeshire",
      "Milton Keynes": "Buckinghamshire",
      "Minehead": "Somerset",
      "Mirfield": "West Yorkshire",
      "Mitcham": "Surrey",
      "Mitcheldean": "Gloucestershire",
      "Mold": "Clwyd",
      "Monmouth": "Gwent",
      "Montgomery": "Powys",
      "Montrose": "Angus",
      "Morden": "Surrey",
      "Morecambe": "Lancashire",
      "Moretonhampstead": "Devon",
      "Morpeth": "Northumberiand",
      "Moscow": "East Ayrshire",
      "Motherwell": "Lanarkshire",
      "Musselburgh": "Midlothian",
      "Nailsea": "Avon",
      "Nairn": "Inverness-shire",
      "Nantwich": "Cheshire",
      "Narberth": "Pembrokeshire",
      "Neath": "Neath Port Talbot",
      "Nefyn": "Gwynedd",
      "Nelson": "Lancashire",
      "Nethy Bridge": "Inverness-shire",
      "New Malden": "Surrey",
      "New Mills": "Derbyshire",
      "Newark": "Nottinghamshire",
      "Newbury": "Berkshire",
      "Newcastle": "Staffordshire",
      "Newcastle Emlyn": "Dyfed",
      "Newcastle upon Tyne": "Tyne and Wear",
      "Newcastleton": "Roxburghshire",
      "Newent": "Gloucestershire",
      "Newhaven": "East Sussex",
      "Newmarket": "Suffolk",
      "Newport": "Shropshire",
      "Newport Pagnell": "Buckinghamshire",
      "Newquay": "Cornwall",
      "Newton Abbot": "Devon",
      "Newtown": "Powys",
      "Newtown-le- Willows": "Merseyside",
      "Newtownabbey": "Co Antrim",
      "Newtownards": "Co Down",
      "North Berwick": "East Lothian",
      "North Shields": "Tyne and Wear",
      "North Walsham": "Norfolk",
      "Northallerton": "North Yorkshire",
      "Northampton": "Northamptonshire",
      "Northwich": "Cheshire",
      "Northwood": "Middlesex",
      "Norwich": "Norfolk",
      "Nottingham": "Nottinghamshire",
      "Nottinghamshire": "Nottinghamshire",
      "Nuneaton": "Warwickshire",
      "Oakham": "Leicestershire",
      "Oban": "Argyll",
      "Okehampton": "Devon",
      "Oldham": "Lancashire",
      "Omagh": "Co Tyrone",
      "Ongar": "Essex",
      "Ormskirk": "Lancashire",
      "Orpington": "Kent",
      "Ossett": "West Yorkshire",
      "Oswestry": "Shropshire",
      "Otley": "West Yorkshire",
      "Oxford": "Oxfordshire",
      "Oxted": "Surrey",
      "Paignton": "Devon",
      "Paisley": "Renfrewshire",
      "Pakenham": "Suffolk",
      "Par": "Cornwall",
      "Pembroke": "Dyfed",
      "Penarth": "South Glamorgan",
      "Pencombe": "Herefordshire",
      "Penicuik": "Midlothian",
      "Penmaenmawr": "Gwynedd",
      "Penrhyndeudraeth": "Gwynedd",
      "Penrith": "Cumbria",
      "Penryn": "Cornwall",
      "Penzance": "Cornwall",
      "Pershore": "Hereford and Worcester",
      "Perth": "Perthshire",
      "Peterborough": "Cambridgeshire",
      "Peterhead": "Aberdeenshire",
      "Petersfield": "Hampshire",
      "Petworth": "West Sussex",
      "Pevensey": "East Sussex",
      "Pewsey": "Wiltshire",
      "Pickering": "North Yorkshire",
      "Pinner": "Middlesex",
      "Pitlochry": "Perthshire",
      "Plymouth": "Devon",
      "Pocklington": "East Riding of Yorkshire",
      "Pontefract": "West Yorkshire",
      "Pontyclun": "Mid Glamorgan",
      "Pontypool": "Torfaen",
      "Pontypridd": "Mid Glamorgan",
      "Poole": "Dorset",
      "Pooley Bridge": "Cumbria",
      "Port Isaac": "Cornwall",
      "Port Talbot": "West Glamorgan",
      "Porthcawl": "Mid Glamorgan",
      "Porthmadog": "Gwynedd",
      "Portree": "Isle of Skye",
      "Portrush": "Co Antrim",
      "Portsmouth": "Hampshire",
      "Potters Bar": "Hertfordshire",
      "Poulton-le-Fylde": "Lancashire",
      "Prescot": "Merseyside",
      "Prestatyn": "Clwyd",
      "Preston": "Lancashire",
      "Prestwick": "Ayrshire",
      "Princes Risborough": "Buckinghamshire",
      "Prudhoe": "Northumberland",
      "Pulborough": "West Sussex",
      "Purley": "Surrey",
      "Pwllheli": "Gwynedd",
      "No Entries": "&nbsp;",
      "Radlett": "Hertfordshire",
      "Ramsey": "Isle of Man",
      "Ramsgate": "Kent",
      "Raughton Head": "Cumbria",
      "Rayleigh": "Essex",
      "Reading": "Berkshire",
      "Redcar": "Cleveland",
      "Redditch": "Hereford and",
      "Redhill": "Surrey",
      "Redruth": "Cornwall",
      "Reigate": "Surrey",
      "Retford": "Nottmghamshire",
      "Rhyl": "Clwyd",
      "Richmond": "Surrey",
      "Rickmansworth": "Hertfordshire",
      "Riding Mill": "Northumberland",
      "Ringwood": "Hampshire",
      "Ripley": "Derbyshire",
      "Ripon": "North Yorkshire",
      "Robertsbridge": "East Sussex",
      "Rochdale": "Lancashire",
      "Rochester": "Kent",
      "Rochford": "Essex",
      "Rockbourne": "Hampshire",
      "Romford": "Essex",
      "Romsey": "Hampshire",
      "Ross-on-Wye": "Herefordshire",
      "Rossendale": "Lancashire",
      "Rothbury": "Northumberland",
      "Rotherham": "South Yorkshire",
      "Rothesay": "Isle ofBute",
      "Royston": "Hertfordshire",
      "Rugby": "Warwickshire",
      "Rugeley": "Staffordshire",
      "Ruislip": "Middlesex",
      "Runcorn": "Cheshire",
      "Rushden": "Northamptonshire",
      "Ruthin": "Clwyd",
      "Rye": "East Sussex",
      "Ryton": "Tyne and Wear",
      "Saffron Walden": "Essex",
      "Salford": "Lancashire",
      "Salisbury": "Wiltshire",
      "Saltash": "Cornwall",
      "Saltburn-by-the-Sea": "Cleveland",
      "Saltcoats": "Ayrshire",
      "Sandbach": "Cheshire",
      "Sandhurst": "Berkshire",
      "Sandown": "Isle of Wight",
      "Sandwich": "Kent",
      "Sandy": "Bedfordshire",
      "Sanquhar": "Dumfriesshire",
      "Sawbridgeworth": "Hertfordshire",
      "Saxmundham": "Suffolk",
      "Scarborough": "North Yorkshire",
      "Scarinish": "Isle of Tiree",
      "Scunthorpe": "South Humberside",
      "Seaford": "East Sussex",
      "Seaham": "Co Durham",
      "Seahouses": "Northumberland",
      "Seaton": "Devon",
      "Sedbergh": "Cumbria",
      "Sedgefield": "Co Durham",
      "Selby": "North Yorkshire",
      "Selkirk": "Selkirkshire",
      "Settle": "North Yorkshire",
      "Sevenoaks": "Kent",
      "Shaftesbury": "Wiltshire",
      "Shap": "Cumbria",
      "Shawbost": "Isle of Lewis",
      "Sheffield": "South Yorkshire",
      "Shepperton": "Middlesex",
      "Shepton Mallet": "Somerset",
      "Sherborne": "Dorset",
      "Sheringham": "Norfolk",
      "Shetland": "Isle of Shetland",
      "Shifnal": "Shropshire",
      "Shipley": "West Yorkshire",
      "Shrewsbury": "Shropshire",
      "Sidcup": "Kent",
      "Sidmouth": "Devon",
      "Sittingbourne": "Kent",
      "Skegness": "Lincolnshire",
      "Skelmersdale": "Lancashire",
      "Skipton": "North Yorkshire",
      "Sleaford": "Lincolnshire",
      "Slough": "Berkshire",
      "Solihull": "West Midlands",
      "South Croydon": "Surrey",
      "South Queensferry": "West Lothian",
      "South Molton": "Devon",
      "South Petherton": "Somerset",
      "South Wirral": "Merseyside",
      "Southall": "Middlesex",
      "Southam": "Warwickshire",
      "Southampton": "Hampshire",
      "Southend-on-Sea": "Essex",
      "Southminster": "Essex",
      "Southport": "Merseyside",
      "Southsea": "Hampshire",
      "Southwell": "Nottinghamshire",
      "Sowerby": "North Yorkshire",
      "Spalding": "Lincolnshire",
      "Spilsby": "Lincolnshire",
      "St Albans": "Hertfordshire",
      "St Andrews": "Fife",
      "St Asaph": "Clwyd",
      "St Austell": "Cornwall",
      "St Clears": "Carmarthenshire",
      "St Helens": "Merseyside",
      "St Ives": "Cornwall",
      "St Leonards-on-Sea": "East Sussex",
      "Stafford": "Staffordshire",
      "Staines": "Middlesex",
      "Stamford": "Lincolnshire",
      "Stanford-le-Hope": "Essex",
      "Stanmore": "Middlesex",
      "Stevenage": "Hertfordshire",
      "Stirling": "Stirlingshire",
      "Stockport": "Cheshire",
      "Stocksfield": "Northumberland",
      "Stockton-on-Tees": "Cleveland",
      "Stoke-on-Trent": "Staffordshire",
      "Stone": "Staffordshire",
      "Stonehaven": "Kincardineshire",
      "Stornoway": "Isle of Lewis",
      "Stourbridge": "West Midlands",
      "Stourport-on-Severn": "Hereford and Worcester",
      "Stow-on-the-Wold": "Gloucestershire",
      "Stowmarket": "Suffolk",
      "Stranraer": "Wigtownshire",
      "Stratford-upon-Avon": "Warwickshire",
      "Strathcarron": "Ross-shire",
      "Strathaven": "South Lanarkshire",
      "Strathpeffer": "Ross-shire",
      "Street": "Somerset",
      "Stroud": "Gloucestershire",
      "Sudbury": "Suffolk",
      "Sunbury-on-Thames": "Middlesex",
      "Sunderland": "Tyne and Wear",
      "Surbiton": "Surrey",
      "Sutton": "Surrey",
      "Sutton Coldfield": "West Midlands",
      "Sutton-in-Ashfield": "Nottinghamshire",
      "Swaffham": "Norfolk",
      "Swanage": "Dorset",
      "Swanley": "Kent",
      "Swansea": "West Glamorgan",
      "Swindon": "Wiltshire",
      "Tain": "Ross-shire",
      "Talybont": "Gwynedd",
      "Tamworth": "Staffordshire",
      "Tarbert": "Argyll",
      "Tarporley": "Cheshire",
      "Taunton": "Somerset",
      "Tavistock": "Devon",
      "Teddington": "Middlesex",
      "Teignmouth": "Devon",
      "Telford": "Shropshire",
      "Temple Cloud": "Somerset",
      "Templecombe": "Somerset",
      "Tenby": "Dyfed",
      "Tewkesbury": "Gloucestershire",
      "Thame": "Oxfordshire",
      "Thanet": "Kent",
      "Thatcham": "Berkshire",
      "Thetford": "Norfolk",
      "Thirsk": "North Yorkshire",
      "Thornton Heath": "Surrey",
      "Thurso": "Caithness",
      "Tilbury": "Essex",
      "Tipton": "West Midlands",
      "Tiverton": "Devon",
      "Tonbridge": "Kent",
      "Torquay": "Devon",
      "Torrington": "Devon",
      "Totland Bay": "Isle of Wight",
      "Towcester": "Northamptonshire",
      "Tranent": "East Lothian",
      "Tredegar": "Gwent",
      "Tring": "Hertfordshire",
      "Trowbridge": "Wiltshire",
      "Truro": "Cornwall",
      "Tunbridge Wells": "Kent",
      "Turriff": "Aberdeenshire",
      "Twickenham": "Middlesex",
      "Tywyn": "Gwynedd",
      "Uckfield": "East Sussex",
      "Ulverston": "Cumbria",
      "Umberleigh": "Devon",
      "Uttoxeter": "Staffordshire",
      "Uxbridge": "Middlesex",
      "Ventnor": "Isle ofWight",
      "Wadebridge": "Cornwall",
      "Wakefield": "West Yorkshire",
      "Wallasey": "Merseyside",
      "Wallingford": "Oxfordshire",
      "Wallington": "Surrey",
      "Walsall": "West Midlands",
      "Walsingham": "Norfolk",
      "Waltham Cross": "Hertfordshire",
      "Walton on the Naze": "Essex",
      "Walton-on-Thames": "Surrey",
      "Wantage": "Oxfordshire",
      "Warboys": "Cambridgeshire",
      "Ware": "Hertfordshire",
      "Wareham": "Dorset",
      "Warley": "West Midlands",
      "Warminster": "Wiltshire",
      "Warrington": "Cheshire",
      "Warwick": "Warwickshire",
      "Warwickshire": "Warwickshire",
      "Washington": "Tyne and Wear",
      "Watchet": "Somerset",
      "Watford": "Hertfordshire",
      "Wedmore": "Somerset",
      "Welling": "Kent",
      "Wellingborough": "Northamptonshire",
      "Wells": "Somerset",
      "Wells-next-the-Sea": "Norfolk",
      "Welshpool": "Powys",
      "Welwyn": "Hertfordshire",
      "Welwyn Garden City": "Hertfordshire",
      "Wem": "Shropshire",
      "Wembley": "Middlesex",
      "West Bromwich": "West Midlands",
      "West Byfleet": "Surrey",
      "West Drayton": "Middlesex",
      "West Heslerton": "North Yorkshire",
      "West Kilbride": "Ayrshire",
      "West Linton": "Peeblesshire",
      "West Malling": "Kent",
      "West Wickham": "Kent",
      "Westbury": "Wiltshire",
      "Westcliff-on-Sea": "Essex",
      "Westerham": "Kent",
      "Weston-super-Mare": "Avon",
      "Wetherby": "West Yorkshire",
      "Weybridge": "Surrey",
      "Weymouth": "Dorset",
      "Whatton": "Nottinghamshire",
      "Whitby": "North Yorkshire",
      "Whitchurch": "Shropshire",
      "Whitehaven": "Cumbria",
      "Whitland": "Dyfed",
      "Whitley Bay": "Tyne and Wear",
      "Whitstable": "Kent",
      "Wick": "Caithness",
      "Wickford": "Essex",
      "Wigan": "Lancashire",
      "Wigton": "Cumbria",
      "Wilmslow": "Cheshire",
      "Wimborne": "Dorset",
      "Wincanton": "Somerset",
      "Winchester": "Hampshire",
      "Windermere": "Cumbria",
      "Windsor": "Berkshire",
      "Winscombe": "Somerset",
      "Wirral": "Merseyside",
      "Wisbech": "Cambridgeshire",
      "Wishaw": "Lanarkshire",
      "Witham": "Essex",
      "Witney": "Oxfordshire",
      "Woking": "Surrey",
      "Wokingham": "Berkshire",
      "Wolverhampton": "West Midlands",
      "Woodford Green": "Essex",
      "Worcester": "Hereford and Worcester",
      "Workington": "Cumbria",
      "Worksop": "Nottinghamshire",
      "Wormbridge": "Herefordshire",
      "Worthing": "West Sussex",
      "Wotton-under-Edge": "Gloucestershire",
      "Wrexham": "Clwyd",
      "Wymondham": "Norfolk",
      "Yateley": "Surrey",
      "Yelverton": "Devon",
      "Yeovil": "Somerset",
      "York": "North Yorkshire"
    }
  };

  /// List of countries
  /// @todo may need translation (?)
  static const Map<String, String> countries = {
    "AF": "Afghanistan",
    "AX": "Åland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, The Democratic Republic of the",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Cote D'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island and Mcdonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic Of",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea, Democratic People'S Republic of",
    "KR": "Korea, Republic of",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People'S Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "Macedonia, The Former Yugoslav Republic of",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States of",
    "MD": "Moldova, Republic of",
    "MC": "Monaco",
    "MN": "Mongolia",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "AN": "Netherlands Antilles",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory, Occupied",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SH": "Saint Helena",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "CS": "Serbia and Montenegro",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia and the South Sandwich Islands",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard and Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan, Province of China",
    "TJ": "Tajikistan",
    "TZ": "Tanzania, United Republic of",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "UK": "United Kingdom",
    "US": "United States",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Viet Nam",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "WF": "Wallis and Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
  };
}