name: adsplatter
description: "Adsplatter's mobile app."
version: 1.0.0+1

repository: https://github.com/adsplatter/mobile
homepage: https://github.com/adsplatter/mobile
issue_tracker: https://github.com/adsplatter/mobile/issues

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Flutter localization (L10n) generator
  flutter_localized_locales: ^2.0.5

  # Persistent storage
  shared_preferences: ^2.2.3

  # Image parsing & more
  image: ^4.2.0

  # Information about the device
  package_info_plus: ^8.0.0

  # Import the Adsplatter's flutter-framework package from GitHub
  framework:
    git:
      url: https://github.com/Adsplatter/flutter-framework

# Other packages
dependency_overrides:
  intl: 0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  mockito: ^5.0.0
  test: ^1.24.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Localization
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/
    - assets/icon/
    - assets/icon/android/
    - assets/icon/android/hdpi/
    - assets/icon/android/mdpi/
    - assets/icon/android/xhdpi/
    - assets/icon/android/xxhdpi/
    - assets/icon/android/xxxhdpi/
    - assets/icon/ios/
    - assets/icon/ios/2x/
    - assets/icon/ios/3x/
    - assets/icon/web/
    - assets/icon/web/24/
    - assets/icon/web/58/
    - assets/icon/web/64/
    - assets/icon/web/256/
    - assets/icon/web/2048/
    - assets/icon/flags/
    - assets/lottiefiles/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
